strings:
  permission: "blockclutch.admin"
  noperm: "&cSorry %p% you do not have permission to do this"
  addedspawnpoint: "&cI have made the spawnpoint %id% sucessfully"
settings:
  enabled: true
scoreboard:
  titles:
  - "&e&lBedwars Practice"
  - "&6&lB&e&ledwars Practice"
  - "&6&lBe&e&ldwars Practice"
  - "&6&lBed&e&lwars Practice"
  - "&6&lBedw&e&lars Practice"
  - "&6&lBedwa&e&lrs Practice"
  - "&6&lBedwar&e&ls Practice"
  - "&6&lBedwars &e&lPractice"
  - "&6&lBedwars P&e&lractice"
  - "&6&lBedwars Pr&e&lactice"
  - "&6&lBedwars Pra&e&lctice"
  - "&6&lBedwars Prac&e&ltice"
  - "&6&lBedwars Pract&e&lice"
  - "&6&lBedwars Practi&e&lce"
  - "&6&lBedwars Practic&e&le"
  - "&6&lBedwars Practice"
  - "&e&lB&6&ledwars Practice"
  - "&e&lBe&6&ldwars Practice"
  - "&e&lBed&6&lwars Practice"
  - "&e&lBedw&6&lars Practice"
  - "&e&lBedwa&6&lrs Practice"
  - "&e&lBedwar&6&ls Practice"
  - "&e&lBedwars &6&lPractice"
  - "&e&lBedwars P&6&lractice"
  - "&e&lBedwars Pr&6&lactice"
  - "&e&lBedwars Pra&6&lctice"
  - "&e&lBedwars Prac&6&ltice"
  - "&e&lBedwars Practi&6&lce"
  - "&e&lBedwars Practic&6&le"

