name: PracticeKnockback
version: 1.0-SNAPSHOT
main: lol.maltest.practiceknockback.PracticeKnockback
authors: [ maltest ]
description: BedwarsPractice BlockClutch Technique Clone
commands:
  setup:
    description: Setup the  shit
  togglebuild:
    description: toggle